import { Project, Task, TeamMember } from '../types';

export const sampleProjects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Redesign company website with modern UI/UX',
    color: '#3b82f6',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Build cross-platform mobile application',
    color: '#10b981',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '3',
    name: 'Marketing Campaign',
    description: 'Q1 2024 marketing and promotional campaign',
    color: '#f59e0b',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
];

export const sampleTasks: Task[] = [
  {
    id: '1',
    title: 'Design homepage mockups',
    description: 'Create initial design concepts for the new homepage',
    status: 'done',
    priority: 'high',
    assignee: 'John Doe',
    dueDate: '2024-03-15',
    createdAt: new Date('2024-01-05').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
    projectId: '1',
  },
  {
    id: '2',
    title: 'Implement navigation component',
    description: 'Build responsive navigation with mobile menu',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Jane Smith',
    dueDate: '2024-03-20',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
    projectId: '1',
  },
  {
    id: '3',
    title: 'Set up development environment',
    description: 'Configure React Native and necessary tooling',
    status: 'done',
    priority: 'urgent',
    assignee: 'Mike Johnson',
    dueDate: '2024-02-01',
    createdAt: new Date('2024-01-16').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
    projectId: '2',
  },
  {
    id: '4',
    title: 'Create user authentication flow',
    description: 'Implement login, signup, and password reset',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Mike Johnson',
    dueDate: '2024-03-10',
    createdAt: new Date('2024-01-25').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
    projectId: '2',
  },
  {
    id: '5',
    title: 'Social media content calendar',
    description: 'Plan content for all social platforms',
    status: 'review',
    priority: 'medium',
    assignee: 'Sarah Williams',
    dueDate: '2024-03-05',
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
    projectId: '3',
  },
  {
    id: '6',
    title: 'Email marketing templates',
    description: 'Design and code responsive email templates',
    status: 'todo',
    priority: 'medium',
    assignee: 'Sarah Williams',
    dueDate: '2024-03-25',
    createdAt: new Date('2024-02-08').toISOString(),
    updatedAt: new Date('2024-02-08').toISOString(),
    projectId: '3',
  },
];

export const sampleTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'UI/UX Designer',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'Frontend Developer',
  },
  {
    id: '3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    role: 'Full Stack Developer',
  },
  {
    id: '4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    role: 'Marketing Manager',
  },
];
